allowBuilds:
  '@firebase/util': true
  protobufjs: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - '@firebase/util'
  - protobufjs
  - puppeteer
